### ISSUE TITLE
How to store file on remote server uploaded via DMS File Field

### ISSUE THREAD

**Issue by bilalahm** [dms-org/web.laravel#1]
In DMS module, how can I upload file to remote CDN e.g. Amazon S3? I am trying to upload files via following code but file is getting saved in my public directory.

```php
$form->field(
    Field::create('image', 'Image')
        ->image()
        ->moveToPathWithRandomFileName('s3://BUCKET/PATH')
)->bindToProperty(PROPERTY::IMAGE)
```

I have added following variables in my .env file

```
AWS_ACCESS_KEY_ID=xxx
AWS_SECRET_ACCESS_KEY=xxx
```

Am I missing something?

**Comment by TimeToogo** [comment]
Have you installed the AWS SDK and registered the stream wrapper?

To install the `aws/aws-sdk-php` [follow these instructions](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/getting-started/installation.html). Or install via composer:

`composer require aws/aws-sdk-php`

A guide about the S3 stream wrapper `s3://` [can be found here](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-stream-wrapper.html).

To register the stream wrapper add the following to your `app/Providers/AppServiceProvider.php`:

```php
$client = new Aws\S3\S3Client([/** options **/]);

// Register the stream wrapper from an S3Client object
$client->registerStreamWrapper();
```
