### ISSUE TITLE
Typo in name SymphonyToDmsUploadedFileTransformer

### ISSUE THREAD

**Issue by harikt** [dms-org/web.laravel#2]
Would you accept fixing the typo `SymphonyToDmsUploadedFileTransformer` to `SymfonyToDmsUploadedFileTransformer` ?

or does this breaks anything at your end ?

If not I can send a PR for the same.

**Comment by TimeToogo** [comment]
Good pickup!

Unfortunately since this class is referenced directly in `config/dms.php` this would break apps already using the DMS. You're welcome to send a pull request but perhaps add a `class_alias` to maintain BC. We can then remove this at some point before the v1.0 release.
