### ISSUE TITLE
Package\Module\TableController@reorderRow

### ISSUE THREAD

**Issue by harikt** [dms-org/web.laravel#5]
In https://github.com/dms-org/web.laravel/blob/b128602ce83d4584caa87ad3fb3f1dd5c6ae0889/src/Http/ModuleRequestRouter.php#L99

there is `Package\Module\TableController@reorderRow`

It looks missing in :  https://github.com/dms-org/web.laravel/blob/master/src/Http/Controllers/Package/Module/TableController.php

Quick search doesn't reveal any.

**Comment by TimeToogo** [comment]
Good pickup, this route has been removed in https://github.com/dms-org/web.laravel/commit/8eb1c8ff0b70fd91e2d0e8685d176d790e0098ab.
